### PR TITLE
Fix issue for large queries

### PR DESCRIPTION
**Pull request by pong1290**
Per #https://techdocs.broadcom.com/us/en/ca-enterprise-software/business-management/ca-service-management/17-1/troubleshooting/troubleshooting-ca-service-desk-manager/how-to-extend-the-ca-sdm-soap-web-services-method-doquery-limitation-of-250-rows.html
so current searchobject function will only return 250 rows. Added secondary searchobject_250 to iterate through results to generate complete results.

### CODE REVIEW

**Comment by jsarver** [comment]
Hi, thanks for your interest and suggested fix! I don't think this is necessary as the method you reference (doQuery) is not the method being used in tthe searchobjects method (doSelect).  It is using doSelect which is the method recommended to use in the document you posted.

> To extend you can use a different method using the CA SDM Web Services doSelect(). The method "doSelect()" will return a "list handle". The "listHandle" can be passed to another call - "getListValues()". This method takes a start index and end index argument. This retrieves 250 rows at a time. However, it is possible to retrieve the next 250 rows and so on, until the entire list is retrieved.
> The examples here shows the XML representation of the SOAP Web Services calls doSelect():

**Comment by pong1290** [comment]
Hi Josh- thanks for responding/reviewing

Actually that part of their doc is wrong.
if you look at this
https://techdocs.broadcom.com/us/en/ca-enterprise-software/business-management/ca-service-management/17-1/reference/ca-service-desk-manager-reference-commands/technical-reference/list-query-methods.html#concept.dita_dffb54bd53ae2427f8458d1b59bb62e92a0a92da_doSelect

doselect does not return a handle, only doquery does. The handle is needed
in order to process return results that are more than 250.
Currently since you specified -1 as the max, doselect will only return max
250 results.

**Comment by jsarver** [comment]
Ok, that is starting to sound vaguely familiar, its actually been forever since i've used this library.  I don't have a way to test this but from what I can see it looks good.  My only feedback would be to change the method name to something a bit more meaningful (maybe doQuery?) OR you could add this code to the existing searchObjects metrhod.  Perhaps if the max < 0 or max > 250 then it would run your code. 

Aside from that I'd recommend maxing the spacing in operations consistent with the rest of the library.  Example below

change
max=query.listLength-1

to this
max = query.listLength - 1

Thanks,
Josh

**Comment by pong1290** [comment]
Thanks for the input. (apologies for the late reply)
I have modified the branch as requested- Let me know if it looks okay to
you.

**Comment by jsarver** [comment]
Looks good, its been merged!  Thanks for you patience and your contribution!

**Pull request merged**
